image: docker:stable

services:
- docker:dind

stages:
  - Build image and push
  - Code quality test
<<<<<<< HEAD

=======
>>>>>>> 739da9685d8f27dfb7a354f00a4ab9e8460602a8
docker build:
  stage: Build image and push
  script:
  - docker build -t aanjan1112/nodejs-backend-server:v1 .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push aanjan1112/nodejs-backend-server:v1

<<<<<<< HEAD
=======

>>>>>>> 739da9685d8f27dfb7a354f00a4ab9e8460602a8
codequality:
  stage: Code quality test
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay
  services:
    - docker:dind
  script:
    - docker pull codeclimate/codeclimate:0.69.0
    - docker run --env CODECLIMATE_CODE="$PWD" --volume "$PWD":/code --volume /var/run/docker.sock:/var/run/docker.sock --volume /tmp/cc:/tmp/cc codeclimate/codeclimate:0.69.0 init
    - docker run --env CODECLIMATE_CODE="$PWD" --volume "$PWD":/code --volume /var/run/docker.sock:/var/run/docker.sock --volume /tmp/cc:/tmp/cc codeclimate/codeclimate:0.69.0 analyze -f json > codeclimate.json || true
  artifacts:
    paths: [codeclimate.json]


